/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v0alpha0

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	kubeagenticnetworkingapiv0alpha0 "sigs.k8s.io/kube-agentic-networking/api/v0alpha0"
	versioned "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/kube-agentic-networking/k8s/client/informers/externalversions/internalinterfaces"
	apiv0alpha0 "sigs.k8s.io/kube-agentic-networking/k8s/client/listers/api/v0alpha0"
)

// KANConfigInformer provides access to a shared informer and lister for
// KANConfigs.
type KANConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv0alpha0.KANConfigLister
}

type kANConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKANConfigInformer constructs a new informer for KANConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKANConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKANConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKANConfigInformer constructs a new informer for KANConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKANConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV0alpha0().KANConfigs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV0alpha0().KANConfigs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV0alpha0().KANConfigs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV0alpha0().KANConfigs(namespace).Watch(ctx, options)
			},
		}, client),
		&kubeagenticnetworkingapiv0alpha0.KANConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *kANConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKANConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kANConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubeagenticnetworkingapiv0alpha0.KANConfig{}, f.defaultInformer)
}

func (f *kANConfigInformer) Lister() apiv0alpha0.KANConfigLister {
	return apiv0alpha0.NewKANConfigLister(f.Informer().GetIndexer())
}
