/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v0alpha0

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	kubeagenticnetworkingapiv0alpha0 "sigs.k8s.io/kube-agentic-networking/api/v0alpha0"
	versioned "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/kube-agentic-networking/k8s/client/informers/externalversions/internalinterfaces"
	apiv0alpha0 "sigs.k8s.io/kube-agentic-networking/k8s/client/listers/api/v0alpha0"
)

// XBackendInformer provides access to a shared informer and lister for
// XBackends.
type XBackendInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv0alpha0.XBackendLister
}

type xBackendInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewXBackendInformer constructs a new informer for XBackend type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewXBackendInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredXBackendInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredXBackendInformer constructs a new informer for XBackend type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredXBackendInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV0alpha0().XBackends(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV0alpha0().XBackends(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV0alpha0().XBackends(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV0alpha0().XBackends(namespace).Watch(ctx, options)
			},
		},
		&kubeagenticnetworkingapiv0alpha0.XBackend{},
		resyncPeriod,
		indexers,
	)
}

func (f *xBackendInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredXBackendInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *xBackendInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubeagenticnetworkingapiv0alpha0.XBackend{}, f.defaultInformer)
}

func (f *xBackendInformer) Lister() apiv0alpha0.XBackendLister {
	return apiv0alpha0.NewXBackendLister(f.Informer().GetIndexer())
}
