/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v0alpha0

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apiv0alpha0 "sigs.k8s.io/kube-agentic-networking/api/v0alpha0"
)

// KANConfigLister helps list KANConfigs.
// All objects returned here must be treated as read-only.
type KANConfigLister interface {
	// List lists all KANConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.KANConfig, err error)
	// KANConfigs returns an object that can list and get KANConfigs.
	KANConfigs(namespace string) KANConfigNamespaceLister
	KANConfigListerExpansion
}

// kANConfigLister implements the KANConfigLister interface.
type kANConfigLister struct {
	listers.ResourceIndexer[*apiv0alpha0.KANConfig]
}

// NewKANConfigLister returns a new KANConfigLister.
func NewKANConfigLister(indexer cache.Indexer) KANConfigLister {
	return &kANConfigLister{listers.New[*apiv0alpha0.KANConfig](indexer, apiv0alpha0.Resource("kanconfig"))}
}

// KANConfigs returns an object that can list and get KANConfigs.
func (s *kANConfigLister) KANConfigs(namespace string) KANConfigNamespaceLister {
	return kANConfigNamespaceLister{listers.NewNamespaced[*apiv0alpha0.KANConfig](s.ResourceIndexer, namespace)}
}

// KANConfigNamespaceLister helps list and get KANConfigs.
// All objects returned here must be treated as read-only.
type KANConfigNamespaceLister interface {
	// List lists all KANConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.KANConfig, err error)
	// Get retrieves the KANConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv0alpha0.KANConfig, error)
	KANConfigNamespaceListerExpansion
}

// kANConfigNamespaceLister implements the KANConfigNamespaceLister
// interface.
type kANConfigNamespaceLister struct {
	listers.ResourceIndexer[*apiv0alpha0.KANConfig]
}
