/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v0alpha0

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apiv0alpha0 "sigs.k8s.io/kube-agentic-networking/api/v0alpha0"
)

// XAccessPolicyLister helps list XAccessPolicies.
// All objects returned here must be treated as read-only.
type XAccessPolicyLister interface {
	// List lists all XAccessPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.XAccessPolicy, err error)
	// XAccessPolicies returns an object that can list and get XAccessPolicies.
	XAccessPolicies(namespace string) XAccessPolicyNamespaceLister
	XAccessPolicyListerExpansion
}

// xAccessPolicyLister implements the XAccessPolicyLister interface.
type xAccessPolicyLister struct {
	listers.ResourceIndexer[*apiv0alpha0.XAccessPolicy]
}

// NewXAccessPolicyLister returns a new XAccessPolicyLister.
func NewXAccessPolicyLister(indexer cache.Indexer) XAccessPolicyLister {
	return &xAccessPolicyLister{listers.New[*apiv0alpha0.XAccessPolicy](indexer, apiv0alpha0.Resource("xaccesspolicy"))}
}

// XAccessPolicies returns an object that can list and get XAccessPolicies.
func (s *xAccessPolicyLister) XAccessPolicies(namespace string) XAccessPolicyNamespaceLister {
	return xAccessPolicyNamespaceLister{listers.NewNamespaced[*apiv0alpha0.XAccessPolicy](s.ResourceIndexer, namespace)}
}

// XAccessPolicyNamespaceLister helps list and get XAccessPolicies.
// All objects returned here must be treated as read-only.
type XAccessPolicyNamespaceLister interface {
	// List lists all XAccessPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.XAccessPolicy, err error)
	// Get retrieves the XAccessPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv0alpha0.XAccessPolicy, error)
	XAccessPolicyNamespaceListerExpansion
}

// xAccessPolicyNamespaceLister implements the XAccessPolicyNamespaceLister
// interface.
type xAccessPolicyNamespaceLister struct {
	listers.ResourceIndexer[*apiv0alpha0.XAccessPolicy]
}
