/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	agenticv1alpha1 "sigs.k8s.io/kube-agentic-networking/api/agentic/v1alpha1"
)

// AccessPolicyLister helps list AccessPolicies.
// All objects returned here must be treated as read-only.
type AccessPolicyLister interface {
	// List lists all AccessPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agenticv1alpha1.AccessPolicy, err error)
	// AccessPolicies returns an object that can list and get AccessPolicies.
	AccessPolicies(namespace string) AccessPolicyNamespaceLister
	AccessPolicyListerExpansion
}

// accessPolicyLister implements the AccessPolicyLister interface.
type accessPolicyLister struct {
	listers.ResourceIndexer[*agenticv1alpha1.AccessPolicy]
}

// NewAccessPolicyLister returns a new AccessPolicyLister.
func NewAccessPolicyLister(indexer cache.Indexer) AccessPolicyLister {
	return &accessPolicyLister{listers.New[*agenticv1alpha1.AccessPolicy](indexer, agenticv1alpha1.Resource("accesspolicy"))}
}

// AccessPolicies returns an object that can list and get AccessPolicies.
func (s *accessPolicyLister) AccessPolicies(namespace string) AccessPolicyNamespaceLister {
	return accessPolicyNamespaceLister{listers.NewNamespaced[*agenticv1alpha1.AccessPolicy](s.ResourceIndexer, namespace)}
}

// AccessPolicyNamespaceLister helps list and get AccessPolicies.
// All objects returned here must be treated as read-only.
type AccessPolicyNamespaceLister interface {
	// List lists all AccessPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agenticv1alpha1.AccessPolicy, err error)
	// Get retrieves the AccessPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agenticv1alpha1.AccessPolicy, error)
	AccessPolicyNamespaceListerExpansion
}

// accessPolicyNamespaceLister implements the AccessPolicyNamespaceLister
// interface.
type accessPolicyNamespaceLister struct {
	listers.ResourceIndexer[*agenticv1alpha1.AccessPolicy]
}
