/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	agenticv1alpha1 "sigs.k8s.io/kube-agentic-networking/api/agentic/v1alpha1"
)

// BackendLister helps list Backends.
// All objects returned here must be treated as read-only.
type BackendLister interface {
	// List lists all Backends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agenticv1alpha1.Backend, err error)
	// Backends returns an object that can list and get Backends.
	Backends(namespace string) BackendNamespaceLister
	BackendListerExpansion
}

// backendLister implements the BackendLister interface.
type backendLister struct {
	listers.ResourceIndexer[*agenticv1alpha1.Backend]
}

// NewBackendLister returns a new BackendLister.
func NewBackendLister(indexer cache.Indexer) BackendLister {
	return &backendLister{listers.New[*agenticv1alpha1.Backend](indexer, agenticv1alpha1.Resource("backend"))}
}

// Backends returns an object that can list and get Backends.
func (s *backendLister) Backends(namespace string) BackendNamespaceLister {
	return backendNamespaceLister{listers.NewNamespaced[*agenticv1alpha1.Backend](s.ResourceIndexer, namespace)}
}

// BackendNamespaceLister helps list and get Backends.
// All objects returned here must be treated as read-only.
type BackendNamespaceLister interface {
	// List lists all Backends in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agenticv1alpha1.Backend, err error)
	// Get retrieves the Backend from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agenticv1alpha1.Backend, error)
	BackendNamespaceListerExpansion
}

// backendNamespaceLister implements the BackendNamespaceLister
// interface.
type backendNamespaceLister struct {
	listers.ResourceIndexer[*agenticv1alpha1.Backend]
}
