/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v0alpha0

import (
	http "net/http"

	rest "k8s.io/client-go/rest"
	apiv0alpha0 "sigs.k8s.io/kube-agentic-networking/api/v0alpha0"
	scheme "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned/scheme"
)

type AgenticV0alpha0Interface interface {
	RESTClient() rest.Interface
	XAccessPoliciesGetter
	XBackendsGetter
}

// AgenticV0alpha0Client is used to interact with features provided by the agentic.prototype.x-k8s.io group.
type AgenticV0alpha0Client struct {
	restClient rest.Interface
}

func (c *AgenticV0alpha0Client) XAccessPolicies(namespace string) XAccessPolicyInterface {
	return newXAccessPolicies(c, namespace)
}

func (c *AgenticV0alpha0Client) XBackends(namespace string) XBackendInterface {
	return newXBackends(c, namespace)
}

// NewForConfig creates a new AgenticV0alpha0Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*AgenticV0alpha0Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new AgenticV0alpha0Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*AgenticV0alpha0Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &AgenticV0alpha0Client{client}, nil
}

// NewForConfigOrDie creates a new AgenticV0alpha0Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AgenticV0alpha0Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AgenticV0alpha0Client for the given RESTClient.
func New(c rest.Interface) *AgenticV0alpha0Client {
	return &AgenticV0alpha0Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := apiv0alpha0.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AgenticV0alpha0Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
