/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v0alpha0

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apiv0alpha0 "sigs.k8s.io/kube-agentic-networking/api/v0alpha0"
	scheme "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned/scheme"
)

// KANConfigsGetter has a method to return a KANConfigInterface.
// A group's client should implement this interface.
type KANConfigsGetter interface {
	KANConfigs(namespace string) KANConfigInterface
}

// KANConfigInterface has methods to work with KANConfig resources.
type KANConfigInterface interface {
	Create(ctx context.Context, kANConfig *apiv0alpha0.KANConfig, opts v1.CreateOptions) (*apiv0alpha0.KANConfig, error)
	Update(ctx context.Context, kANConfig *apiv0alpha0.KANConfig, opts v1.UpdateOptions) (*apiv0alpha0.KANConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kANConfig *apiv0alpha0.KANConfig, opts v1.UpdateOptions) (*apiv0alpha0.KANConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv0alpha0.KANConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv0alpha0.KANConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv0alpha0.KANConfig, err error)
	KANConfigExpansion
}

// kANConfigs implements KANConfigInterface
type kANConfigs struct {
	*gentype.ClientWithList[*apiv0alpha0.KANConfig, *apiv0alpha0.KANConfigList]
}

// newKANConfigs returns a KANConfigs
func newKANConfigs(c *AgenticV0alpha0Client, namespace string) *kANConfigs {
	return &kANConfigs{
		gentype.NewClientWithList[*apiv0alpha0.KANConfig, *apiv0alpha0.KANConfigList](
			"kanconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv0alpha0.KANConfig { return &apiv0alpha0.KANConfig{} },
			func() *apiv0alpha0.KANConfigList { return &apiv0alpha0.KANConfigList{} },
		),
	}
}
