/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v0alpha0

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apiv0alpha0 "sigs.k8s.io/kube-agentic-networking/api/v0alpha0"
	scheme "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned/scheme"
)

// XAccessPoliciesGetter has a method to return a XAccessPolicyInterface.
// A group's client should implement this interface.
type XAccessPoliciesGetter interface {
	XAccessPolicies(namespace string) XAccessPolicyInterface
}

// XAccessPolicyInterface has methods to work with XAccessPolicy resources.
type XAccessPolicyInterface interface {
	Create(ctx context.Context, xAccessPolicy *apiv0alpha0.XAccessPolicy, opts v1.CreateOptions) (*apiv0alpha0.XAccessPolicy, error)
	Update(ctx context.Context, xAccessPolicy *apiv0alpha0.XAccessPolicy, opts v1.UpdateOptions) (*apiv0alpha0.XAccessPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, xAccessPolicy *apiv0alpha0.XAccessPolicy, opts v1.UpdateOptions) (*apiv0alpha0.XAccessPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv0alpha0.XAccessPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv0alpha0.XAccessPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv0alpha0.XAccessPolicy, err error)
	XAccessPolicyExpansion
}

// xAccessPolicies implements XAccessPolicyInterface
type xAccessPolicies struct {
	*gentype.ClientWithList[*apiv0alpha0.XAccessPolicy, *apiv0alpha0.XAccessPolicyList]
}

// newXAccessPolicies returns a XAccessPolicies
func newXAccessPolicies(c *AgenticV0alpha0Client, namespace string) *xAccessPolicies {
	return &xAccessPolicies{
		gentype.NewClientWithList[*apiv0alpha0.XAccessPolicy, *apiv0alpha0.XAccessPolicyList](
			"xaccesspolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv0alpha0.XAccessPolicy { return &apiv0alpha0.XAccessPolicy{} },
			func() *apiv0alpha0.XAccessPolicyList { return &apiv0alpha0.XAccessPolicyList{} },
		),
	}
}
