/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v0alpha0

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apiv0alpha0 "sigs.k8s.io/kube-agentic-networking/api/v0alpha0"
	scheme "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned/scheme"
)

// XBackendsGetter has a method to return a XBackendInterface.
// A group's client should implement this interface.
type XBackendsGetter interface {
	XBackends(namespace string) XBackendInterface
}

// XBackendInterface has methods to work with XBackend resources.
type XBackendInterface interface {
	Create(ctx context.Context, xBackend *apiv0alpha0.XBackend, opts v1.CreateOptions) (*apiv0alpha0.XBackend, error)
	Update(ctx context.Context, xBackend *apiv0alpha0.XBackend, opts v1.UpdateOptions) (*apiv0alpha0.XBackend, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, xBackend *apiv0alpha0.XBackend, opts v1.UpdateOptions) (*apiv0alpha0.XBackend, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv0alpha0.XBackend, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv0alpha0.XBackendList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv0alpha0.XBackend, err error)
	XBackendExpansion
}

// xBackends implements XBackendInterface
type xBackends struct {
	*gentype.ClientWithList[*apiv0alpha0.XBackend, *apiv0alpha0.XBackendList]
}

// newXBackends returns a XBackends
func newXBackends(c *AgenticV0alpha0Client, namespace string) *xBackends {
	return &xBackends{
		gentype.NewClientWithList[*apiv0alpha0.XBackend, *apiv0alpha0.XBackendList](
			"xbackends",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv0alpha0.XBackend { return &apiv0alpha0.XBackend{} },
			func() *apiv0alpha0.XBackendList { return &apiv0alpha0.XBackendList{} },
		),
	}
}
