/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apiagenticv1alpha1 "sigs.k8s.io/kube-agentic-networking/api/agentic/v1alpha1"
	versioned "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/kube-agentic-networking/k8s/client/informers/externalversions/internalinterfaces"
	agenticv1alpha1 "sigs.k8s.io/kube-agentic-networking/k8s/client/listers/agentic/v1alpha1"
)

// AccessPolicyInformer provides access to a shared informer and lister for
// AccessPolicies.
type AccessPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() agenticv1alpha1.AccessPolicyLister
}

type accessPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAccessPolicyInformer constructs a new informer for AccessPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAccessPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAccessPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAccessPolicyInformer constructs a new informer for AccessPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAccessPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV1alpha1().AccessPolicies(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV1alpha1().AccessPolicies(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV1alpha1().AccessPolicies(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV1alpha1().AccessPolicies(namespace).Watch(ctx, options)
			},
		},
		&apiagenticv1alpha1.AccessPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *accessPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAccessPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *accessPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiagenticv1alpha1.AccessPolicy{}, f.defaultInformer)
}

func (f *accessPolicyInformer) Lister() agenticv1alpha1.AccessPolicyLister {
	return agenticv1alpha1.NewAccessPolicyLister(f.Informer().GetIndexer())
}
