resources:
- "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
  name: "{{.SdsConfigName}}"
  validation_context:
    trusted_ca:
      filename: "{{.SpiffeMountPath}}/{{.SpiffeTrustBundleFileName}}"
