/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	agenticv1alpha1 "sigs.k8s.io/kube-agentic-networking/api/agentic/v1alpha1"
	scheme "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned/scheme"
)

// AccessPoliciesGetter has a method to return a AccessPolicyInterface.
// A group's client should implement this interface.
type AccessPoliciesGetter interface {
	AccessPolicies(namespace string) AccessPolicyInterface
}

// AccessPolicyInterface has methods to work with AccessPolicy resources.
type AccessPolicyInterface interface {
	Create(ctx context.Context, accessPolicy *agenticv1alpha1.AccessPolicy, opts v1.CreateOptions) (*agenticv1alpha1.AccessPolicy, error)
	Update(ctx context.Context, accessPolicy *agenticv1alpha1.AccessPolicy, opts v1.UpdateOptions) (*agenticv1alpha1.AccessPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, accessPolicy *agenticv1alpha1.AccessPolicy, opts v1.UpdateOptions) (*agenticv1alpha1.AccessPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*agenticv1alpha1.AccessPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*agenticv1alpha1.AccessPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *agenticv1alpha1.AccessPolicy, err error)
	AccessPolicyExpansion
}

// accessPolicies implements AccessPolicyInterface
type accessPolicies struct {
	*gentype.ClientWithList[*agenticv1alpha1.AccessPolicy, *agenticv1alpha1.AccessPolicyList]
}

// newAccessPolicies returns a AccessPolicies
func newAccessPolicies(c *AgenticV1alpha1Client, namespace string) *accessPolicies {
	return &accessPolicies{
		gentype.NewClientWithList[*agenticv1alpha1.AccessPolicy, *agenticv1alpha1.AccessPolicyList](
			"accesspolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *agenticv1alpha1.AccessPolicy { return &agenticv1alpha1.AccessPolicy{} },
			func() *agenticv1alpha1.AccessPolicyList { return &agenticv1alpha1.AccessPolicyList{} },
		),
	}
}
